### ISSUE TITLE
New styles needed for the Web page

### ISSUE THREAD

**Issue by Shubham0812** [Shubham0812/Color-Guesser#1]
On starting the game, there are 2 modes of game displayed "**Easy**" and "**Hard**". 

It would be great if anyone can add images / better colors to make it interesting.

**Comment by norbertzajac** [comment]
I will take it, if still available :)

**Comment by Shubham0812** [comment]
Yeah sure, go ahead 😄

**Comment by alam3211** [comment]
can i improve it too?

**Comment by Shubham0812** [comment]
> can i improve it too?

yeah @alam3211  there's still room for improvement. :D
